version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Part1-Develop-App"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/Part2-Deploy-App-to-VM"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/Part3-Deploy-App-to-Mig"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/Part4-Secure-App-with-SSL"
    schedule:
      interval: "weekly"
